<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\SportsField;

class SportsFieldDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Exact field data from CSV file - 34 fields total
        $fields = [
            [
                'name' => 'Gulshan Youth Club',
                'sport_type' => 'football',
                'description' => 'Professional football field with excellent facilities',
                'type' => 'outdoor',
                'location' => 'Gulshan-2',
                'address' => 'Road:109,Play ground, Dhaka 1212',
                'size' => '7-a-side',
                'surface' => 'Artificial Turf',
                'price_per_90min' => 8000.00,
                'status' => 'active',
                'opening_time' => '09:00:00',
                'closing_time' => '22:00:00',
            ],
            [
                'name' => 'Gulshan Youth Club',
                'sport_type' => 'badminton',
                'description' => 'Professional badminton court with excellent facilities',
                'type' => 'indoor',
                'location' => 'Gulshan-2',
                'address' => 'Road:109,Play ground, Dhaka 1212',
                'size' => 'Full Size',
                'surface' => 'Indoor Court',
                'price_per_90min' => 5000.00,
                'status' => 'active',
                'opening_time' => '09:00:00',
                'closing_time' => '22:00:00',
            ],
            [
                'name' => 'Gulshan Youth Club',
                'sport_type' => 'tabletennis',
                'description' => 'Professional table tennis facility',
                'type' => 'indoor',
                'location' => 'Gulshan-2',
                'address' => 'Road:109,Play ground, Dhaka 1212',
                'size' => 'Full Size',
                'surface' => 'Indoor Court',
                'price_per_90min' => 3000.00,
                'status' => 'active',
                'opening_time' => '09:00:00',
                'closing_time' => '22:00:00',
            ],
            [
                'name' => 'Gulshan Youth Club',
                'sport_type' => 'basketball',
                'description' => 'Professional basketball court',
                'type' => 'outdoor',
                'location' => 'Gulshan-2',
                'address' => 'Road:109,Play ground, Dhaka 1212',
                'size' => 'Full Size',
                'surface' => 'Outdoor Court',
                'price_per_90min' => 3000.00,
                'status' => 'active',
                'opening_time' => '09:00:00',
                'closing_time' => '22:00:00',
            ],
            [
                'name' => 'Swat FC Field',
                'sport_type' => 'football',
                'description' => 'Professional football field with grass surface',
                'type' => 'outdoor',
                'location' => 'Banani',
                'address' => 'QCR3+QXQ, Dhaka 1212',
                'size' => '7-a-side',
                'surface' => 'Grass',
                'price_per_90min' => 1000.00,
                'status' => 'active',
                'opening_time' => '09:00:00',
                'closing_time' => '18:00:00',
            ],
            [
                'name' => 'JAFF Arena & Academy',
                'sport_type' => 'football',
                'description' => 'Professional football academy with artificial turf',
                'type' => 'outdoor',
                'location' => 'Bashundhara',
                'address' => 'RC6F+RR6, Bashundhara Main Gate, Dhaka 1229',
                'size' => '5-a-side',
                'surface' => 'Artificial Turf',
                'price_per_90min' => 6000.00,
                'status' => 'active',
                'opening_time' => '06:30:00',
                'closing_time' => '23:00:00',
            ],
            [
                'name' => 'Sports Grill',
                'sport_type' => 'football',
                'description' => 'Professional football facility with artificial turf',
                'type' => 'outdoor',
                'location' => 'Bashundhara',
                'address' => 'Plot- 17/K Road-9, Dhaka 1229',
                'size' => '7-a-side',
                'surface' => 'Artificial Turf',
                'price_per_90min' => 7000.00,
                'status' => 'active',
                'opening_time' => '06:30:00',
                'closing_time' => '22:00:00',
            ],
            [
                'name' => 'NDE Sports Facility',
                'sport_type' => 'football',
                'description' => 'Professional football facility with artificial turf',
                'type' => 'outdoor',
                'location' => 'Bashundhara',
                'address' => 'RCGM+67M, Rd - 5, Dhaka 1229',
                'size' => '5-a-side',
                'surface' => 'Artificial Turf',
                'price_per_90min' => 5000.00,
                'status' => 'active',
                'opening_time' => '08:30:00',
                'closing_time' => '22:00:00',
            ],
            [
                'name' => 'NDE Sports Facility',
                'sport_type' => 'cricket',
                'description' => 'Professional cricket facility with artificial turf',
                'type' => 'outdoor',
                'location' => 'Bashundhara',
                'address' => 'RCGM+67M, Rd - 5, Dhaka 1229',
                'size' => 'Full Size',
                'surface' => 'Artificial Turf',
                'price_per_90min' => 5000.00,
                'status' => 'active',
                'opening_time' => '08:30:00',
                'closing_time' => '22:00:00',
            ],
            [
                'name' => 'A&A MS Ground Venue-1',
                'sport_type' => 'football',
                'description' => 'Professional football field with grass surface',
                'type' => 'outdoor',
                'location' => 'Khilkhet',
                'address' => 'RCMM+GJ2 Lake City Concord, Lake City Concord, Dhaka 1229',
                'size' => '11-a-side',
                'surface' => 'Grass',
                'price_per_90min' => 6000.00,
                'status' => 'active',
                'opening_time' => '08:00:00',
                'closing_time' => '22:00:00',
            ],
            [
                'name' => 'A&A MS Ground Venue-1',
                'sport_type' => 'football',
                'description' => 'Professional football field with artificial turf',
                'type' => 'outdoor',
                'location' => 'Khilkhet',
                'address' => 'RCMM+GJ2 Lake City Concord, Lake City Concord, Dhaka 1229',
                'size' => '5-a-side',
                'surface' => 'Artificial Turf',
                'price_per_90min' => 5000.00,
                'status' => 'active',
                'opening_time' => '08:00:00',
                'closing_time' => '22:00:00',
            ],
            [
                'name' => 'Dhaka Arena',
                'sport_type' => 'football',
                'description' => 'Professional football field with grass surface',
                'type' => 'outdoor',
                'location' => 'Purbachal',
                'address' => 'Road - 8, Swadesh Shornali Abashon, Purbachal 300ft express road, Dhaka',
                'size' => '11-a-side',
                'surface' => 'Grass',
                'price_per_90min' => 6000.00,
                'status' => 'active',
                'opening_time' => '19:00:00',
                'closing_time' => '23:00:00',
            ],
            [
                'name' => 'Chef\'s Table Courtside',
                'sport_type' => 'football',
                'description' => 'Professional football facility with artificial turf',
                'type' => 'outdoor',
                'location' => '100ft',
                'address' => '100 feet road Madani Ave, Dhaka',
                'size' => '5-a-side',
                'surface' => 'Artificial Turf',
                'price_per_90min' => 5000.00,
                'status' => 'active',
                'opening_time' => '11:00:00',
                'closing_time' => '23:00:00',
            ],
            [
                'name' => 'Chef\'s Table Courtside',
                'sport_type' => 'football',
                'description' => 'Professional football field with grass surface',
                'type' => 'outdoor',
                'location' => '100ft',
                'address' => '100 feet road Madani Ave, Dhaka',
                'size' => '7-a-side',
                'surface' => 'Grass',
                'price_per_90min' => 9000.00,
                'status' => 'active',
                'opening_time' => '11:00:00',
                'closing_time' => '23:00:00',
            ],
            [
                'name' => 'False Nine',
                'sport_type' => 'football',
                'description' => 'Professional football facility with artificial turf',
                'type' => 'outdoor',
                'location' => '100ft',
                'address' => 'Madani Ave, Dhaka 1212',
                'size' => '5-a-side',
                'surface' => 'Artificial Turf',
                'price_per_90min' => 5000.00,
                'status' => 'active',
                'opening_time' => '11:00:00',
                'closing_time' => '23:00:00',
            ],
            [
                'name' => 'ATHLETE\'S HUB',
                'sport_type' => 'football',
                'description' => 'Professional football facility with artificial turf',
                'type' => 'outdoor',
                'location' => '100ft',
                'address' => '100 Feet Road, Beraid Bridge, Dhaka',
                'size' => '7-a-side',
                'surface' => 'Artificial Turf',
                'price_per_90min' => 5000.00,
                'status' => 'active',
                'opening_time' => '08:00:00',
                'closing_time' => '23:00:00',
            ],
            [
                'name' => 'ATHLETE\'S HUB',
                'sport_type' => 'badminton',
                'description' => 'Professional badminton court',
                'type' => 'outdoor',
                'location' => '100ft',
                'address' => '100 Feet Road, Beraid Bridge, Dhaka',
                'size' => 'Full Size',
                'surface' => 'Outdoor Court',
                'price_per_90min' => 3000.00,
                'status' => 'active',
                'opening_time' => '08:00:00',
                'closing_time' => '23:00:00',
            ],
            [
                'name' => 'ATHLETE\'S HUB',
                'sport_type' => 'paddle',
                'description' => 'Professional paddle tennis court',
                'type' => 'outdoor',
                'location' => '100ft',
                'address' => '100 Feet Road, Beraid Bridge, Dhaka',
                'size' => 'Full Size',
                'surface' => 'Outdoor Court',
                'price_per_90min' => 3000.00,
                'status' => 'active',
                'opening_time' => '08:00:00',
                'closing_time' => '23:00:00',
            ],
            [
                'name' => 'ATHLETE\'S HUB',
                'sport_type' => 'cricket',
                'description' => 'Professional cricket facility with artificial turf',
                'type' => 'outdoor',
                'location' => '100ft',
                'address' => '100 Feet Road, Beraid Bridge, Dhaka',
                'size' => 'Full Size',
                'surface' => 'Artificial Turf',
                'price_per_90min' => 4000.00,
                'status' => 'active',
                'opening_time' => '08:00:00',
                'closing_time' => '23:00:00',
            ],
            [
                'name' => 'Metroplex Sporting',
                'sport_type' => 'cricket',
                'description' => 'Professional cricket facility with indoor court',
                'type' => 'indoor',
                'location' => 'Purbachal',
                'address' => 'RCPX+6QJ, Dhaka 1219',
                'size' => 'Full Size',
                'surface' => 'Indoor Court',
                'price_per_90min' => 5000.00,
                'status' => 'active',
                'opening_time' => '10:00:00',
                'closing_time' => '23:00:00',
            ],
            [
                'name' => 'Metroplex Sporting',
                'sport_type' => 'football',
                'description' => 'Professional football facility with artificial turf',
                'type' => 'outdoor',
                'location' => 'Purbachal',
                'address' => 'RCPX+6QJ, Dhaka 1219',
                'size' => '5-a-side',
                'surface' => 'Artificial Turf',
                'price_per_90min' => 7000.00,
                'status' => 'active',
                'opening_time' => '10:00:00',
                'closing_time' => '23:00:00',
            ],
            [
                'name' => 'Metroplex Sporting',
                'sport_type' => 'badminton',
                'description' => 'Professional badminton court with indoor facility',
                'type' => 'indoor',
                'location' => 'Purbachal',
                'address' => 'RCPX+6QJ, Dhaka 1219',
                'size' => 'Full Size',
                'surface' => 'Indoor Court',
                'price_per_90min' => 4000.00,
                'status' => 'active',
                'opening_time' => '10:00:00',
                'closing_time' => '23:00:00',
            ],
            [
                'name' => 'Nutmeg Field',
                'sport_type' => 'football',
                'description' => 'Professional football field with grass surface',
                'type' => 'outdoor',
                'location' => '100ft',
                'address' => 'Sunvalley Abashon-Swadesh-Project, Road:5/A Block:B, Dhaka',
                'size' => '11-a-side',
                'surface' => 'Grass',
                'price_per_90min' => 7000.00,
                'status' => 'active',
                'opening_time' => '10:00:00',
                'closing_time' => '23:00:00',
            ],
            [
                'name' => 'Pacific Sports Ground',
                'sport_type' => 'football',
                'description' => 'Professional football facility with artificial turf',
                'type' => 'outdoor',
                'location' => 'Bashundhara',
                'address' => 'Plot 965-1004, Road No. 15, Dhaka 1215',
                'size' => '7-a-side',
                'surface' => 'Artificial Turf',
                'price_per_90min' => 6000.00,
                'status' => 'active',
                'opening_time' => '10:00:00',
                'closing_time' => '23:00:00',
            ],
            [
                'name' => 'Bashundhara Sports City',
                'sport_type' => 'football',
                'description' => 'Professional football facility with artificial turf',
                'type' => 'outdoor',
                'location' => 'Bashundhara',
                'address' => 'Plot -01, Block N, Bashundhara R/A, Dhaka-1229',
                'size' => '7-a-side',
                'surface' => 'Artificial Turf',
                'price_per_90min' => 6000.00,
                'status' => 'active',
                'opening_time' => '10:00:00',
                'closing_time' => '23:00:00',
            ],
            [
                'name' => 'Bashundhara Sports City',
                'sport_type' => 'cricket',
                'description' => 'Professional cricket facility with artificial turf',
                'type' => 'outdoor',
                'location' => 'Bashundhara',
                'address' => 'Plot -01, Block N, Bashundhara R/A, Dhaka-1229',
                'size' => 'Full Size',
                'surface' => 'Artificial Turf',
                'price_per_90min' => 10000.00,
                'status' => 'active',
                'opening_time' => '10:00:00',
                'closing_time' => '23:00:00',
            ],
            [
                'name' => 'Bashundhara Sports City',
                'sport_type' => 'badminton',
                'description' => 'Professional badminton court with indoor facility',
                'type' => 'indoor',
                'location' => 'Bashundhara',
                'address' => 'Plot -01, Block N, Bashundhara R/A, Dhaka-1229',
                'size' => 'Full Size',
                'surface' => 'Indoor Court',
                'price_per_90min' => 5000.00,
                'status' => 'active',
                'opening_time' => '10:00:00',
                'closing_time' => '23:00:00',
            ],
            [
                'name' => 'Bashundhara Sports City',
                'sport_type' => 'paddle',
                'description' => 'Professional paddle tennis court',
                'type' => 'outdoor',
                'location' => 'Bashundhara',
                'address' => 'Plot -01, Block N, Bashundhara R/A, Dhaka-1229',
                'size' => 'Full Size',
                'surface' => 'Outdoor Court',
                'price_per_90min' => 8000.00,
                'status' => 'active',
                'opening_time' => '10:00:00',
                'closing_time' => '23:00:00',
            ],
            [
                'name' => 'Chattoturf Bashundhara',
                'sport_type' => 'football',
                'description' => 'Professional football facility with artificial turf',
                'type' => 'outdoor',
                'location' => 'Bashundhara',
                'address' => 'Bashundhara R/A , Dhaka , B222 Road No 6, Dhaka 1229',
                'size' => '5-a-side',
                'surface' => 'Artificial Turf',
                'price_per_90min' => 5000.00,
                'status' => 'active',
                'opening_time' => '10:00:00',
                'closing_time' => '23:00:00',
            ],
            [
                'name' => 'OFFSIDE',
                'sport_type' => 'football',
                'description' => 'Professional football facility with artificial turf',
                'type' => 'outdoor',
                'location' => 'Vatara',
                'address' => '422 Abdus Sobhan Dhali Rd, Dhaka 1212',
                'size' => '5-a-side',
                'surface' => 'Artificial Turf',
                'price_per_90min' => 6000.00,
                'status' => 'active',
                'opening_time' => '10:00:00',
                'closing_time' => '23:00:00',
            ],
            [
                'name' => 'DBox Sports Complex',
                'sport_type' => 'football',
                'description' => 'Professional football facility with artificial turf',
                'type' => 'outdoor',
                'location' => 'Mirpur',
                'address' => 'Plot no 217, Block, B B Rd No. 3, Dhaka 1216',
                'size' => '5-a-side',
                'surface' => 'Artificial Turf',
                'price_per_90min' => 6000.00,
                'status' => 'active',
                'opening_time' => '10:00:00',
                'closing_time' => '23:00:00',
            ],
            [
                'name' => 'GreenVill Futsal',
                'sport_type' => 'football',
                'description' => 'Professional football facility with artificial turf',
                'type' => 'outdoor',
                'location' => '100ft',
                'address' => 'East of Chef\'s Table & United House, Madani Avenue, Satarkul (100 feet, 3 km East of US Embassy, Dhaka 1212',
                'size' => '5-a-side',
                'surface' => 'Artificial Turf',
                'price_per_90min' => 5000.00,
                'status' => 'active',
                'opening_time' => '10:00:00',
                'closing_time' => '23:00:00',
            ],
            [
                'name' => 'Amin Mohammad Cricket Club (AMCC)',
                'sport_type' => 'cricket',
                'description' => 'Professional cricket facility with grass surface',
                'type' => 'outdoor',
                'location' => '100ft',
                'address' => 'Satarkul, 100 feet road, Madani Ave, Dhaka',
                'size' => 'Full Size',
                'surface' => 'Grass',
                'price_per_90min' => 7000.00,
                'status' => 'active',
                'opening_time' => '10:00:00',
                'closing_time' => '23:00:00',
            ],
            [
                'name' => 'Tackle Ground',
                'sport_type' => 'football',
                'description' => 'Professional football facility with artificial turf',
                'type' => 'outdoor',
                'location' => 'Banasree',
                'address' => '13, Block - N, Plot No- 17, Road No - Avenue, Sector- 3 Jahurul Islam City, Dhaka 1212',
                'size' => '7-a-side',
                'surface' => 'Artificial Turf',
                'price_per_90min' => 5000.00,
                'status' => 'active',
                'opening_time' => '10:00:00',
                'closing_time' => '23:00:00',
            ],
        ];

        foreach ($fields as $field) {
            SportsField::create($field);
        }
    }
}
